### ISSUE TITLE
Time inject issue

### ISSUE THREAD

**Issue by YorickErnst** [HM-RedMatic/node-red-contrib-sun-position#3]
Hi,

I've set up a time-inject to turn on my lights in the morning during working days. But it seems to trigger on Saturdays as well no matter which combination of days I select (Timestamp-based).

**Comment by Hypnos3** [comment]
I'm try to reproduce this, and I was not able.
Can you please provide me he testcase?

**Comment by Hypnos3** [comment]
When reviewing the code again, I noticed that the current day is determined as UTC timestamp.

If the time stamp is at midnight, erroneous results may occur. I have eliminated this problem with version 0.1.8.
Could you please test with this Version again?

**Comment by YorickErnst** [comment]
Still no luck. Can the system locale have an impact? It is currently set to "nl_BE", but I didn't see any change with en_US when testing.

Here is the config
![capture](https://user-images.githubusercontent.com/43388025/49720359-d9bdfe00-fc5f-11e8-92fa-497edb2f29e5.JPG)

`[{"id":"391f3880.3a2938","type":"time-inject","z":"c1d56eac.9d2f3","name":"Alarm Clock","positionConfig":"51b4d50a.37addc","payload":"true","payloadType":"bool","topic":"A","time":"05:30","timeType":"entered","timeDays":"1","offset":0,"offsetMultiplier":60,"property":"","propertyType":"none","timeAlt":"","timeAltType":"entered","timeAltOffset":0,"timeAltOffsetMultiplier":60,"once":false,"onceDelay":0.1,"recalcTime":2,"x":450,"y":380,"wires":[["ef469c96.8634"]]},{"id":"51b4d50a.37addc","type":"position-config","z":0,"name":"Sun-Aalst","longitude":"4.041","latitude":"50.9378","angleType":"deg","timezoneOffset":"1"}]`

**Comment by Hypnos3** [comment]
Thank you, I will check!

**Comment by Hypnos3** [comment]
The issue should be fixed with the latest version.

**Comment by YorickErnst** [comment]
Dear,

It seems that it is indeed fixed now. Thanks :)
