### ISSUE TITLE
time inject node ignores offset

### ISSUE THREAD

**Issue by FordAndii** [HM-RedMatic/node-red-contrib-sun-position#5]
Hi, I use the time inject node and defined an offset (sunset + 25 minutes). My expectation was that the node fires 25 minutes after sunset. So, as sunset is at 6:19 p.m., the node should fire at 6:44 p.m.

However, the node fires already at sunset without any offset. See attached:

![nodes_sun](https://user-images.githubusercontent.com/48220859/53754155-666d0680-3eb3-11e9-8d98-218895307101.PNG)

The node configuration is as follows:

![node_config](https://user-images.githubusercontent.com/48220859/53754181-77b61300-3eb3-11e9-8af4-334c8975142c.PNG)

**Comment by Hypnos3** [comment]
Danke für die infos.
Der Fehler ist jetzt mit node-red-contrib-sun-position 0.2.5 behoben!

**Comment by Hypnos3** [comment]
Thank you for your issue request.

I have found the error and hopefully fixed in version 0.2.5 .

**Comment by FordAndii** [comment]
I confirm that version 0.2.5 is working perfectly. Thank you!
