### ISSUE TITLE
Time inject node: 1 day offset?

### ISSUE THREAD

**Issue by FordAndii** [HM-RedMatic/node-red-contrib-sun-position#7]
Hi,

it looks like the time inject node has a 1-day offset with respect to the selected days. For example, the first node in the picture is defined to fire monday to friday at sunrise. However, the node announces that its next activation will be on sunrise of 10 March, which is a Sunday.

![time_inject](https://user-images.githubusercontent.com/48220859/54032332-96692200-41b1-11e9-90d0-3a564a843038.PNG)

The bottom node, which is defined to fire on saturday and sunday at 8:02 a.m., did fire today, i.e. Friday, at 8:02 a.m.

So, it looks like when I define the time inject node to fire on day x, it will interpret this as an instruction to fire on day x-1.

**Comment by Hypnos3** [comment]
On my system it is working properly:
![image](https://user-images.githubusercontent.com/12692680/54053552-e6fb7200-41e7-11e9-8493-a45c7cc01381.png)

Which Version do you ise? 0.2.5
Has you set the right time on the enviroment, where node-red is running?

**Comment by FordAndii** [comment]
Hi, system time is fine, version is 0.2.5.

I just noticed the following:

This is what the checkboxes in the node settings look like:

![1](https://user-images.githubusercontent.com/48220859/54072142-cd553b80-4276-11e9-8cae-27f765a229a8.PNG)

It looks strange that the labels start with "Tuesday" and end with "Monday". One would expect them to start with "Monday" and end with "Sunday".

When I apply these settings as shown above, the node label automatically looks like this:

![2](https://user-images.githubusercontent.com/48220859/54072143-cd553b80-4276-11e9-866f-4aa5850dcfc7.PNG)

So, it looks like the checkbox labels in the node settings have an offset.

**Comment by Hypnos3** [comment]
Jea, that is the bug.

In english it is as fllowing:
![image](https://user-images.githubusercontent.com/12692680/54090528-5357ac00-4375-11e9-9d5a-c31ff0ea5e70.png)

There is only the labeling of the checkboxes wrong. There is in the german translation the names postponed. Dienstag is internally monday and so on.

I will fix in next version (can't fix today, caused of problems with github access).

**Comment by Hypnos3** [comment]
This should be fixed now with version 0.2.6.

**Comment by FordAndii** [comment]
Fix confirmed. Thank you!
